language: objective-c
osx_image: xcode9
xcode_project: SafeKeyboard.xcodeproj
xcode_scheme: SafeKeyboard

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- PROJECT=SafeKeyboard.xcodeproj
- SCHEME=SafeKeyboard

script:
- xcodebuild clean build -project "$PROJECT"  -scheme "$SCHEME"
