language: objective-c
osx_image: xcode9
xcode_project: SafeKeyboard.xcodeproj
xcode_scheme: SafeKeyboard

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version
- PROJECT=SafeKeyboard.xcodeproj
- SCHEME=SafeKeyboard

script:
- set -o pipefail
- xcodebuild clean build -project "$PROJECT"  -scheme "$SCHEME" | xcpretty
